var pottyDog={ID: 59269022,
age:"Baby",
barking:5,
breed:"Husky",
description:"Blue is a smart and lovable pup who loves to play with my resident cat and just about anyone he...",
energy:5,
maxHeightFemale:23.5,
maxHeightMale:23.5,
maxWeightFemale:50,
maxWeightMale:60,
minHeightFemale:21,
minHeightMale:21,
minWeightFemale:35,
minWeightMale:45,
name:"Blue",
photo:"https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/59269022/1/?bust=1673471060",
playfulness:5,
protectiveness:1,
sex:"Male",
size:"Small",
status:"adoptable",
trainability:3,
trained:true}